### ISSUE TITLE
File Selector Resizing

### ISSUE THREAD

**Issue by persaud29** [Jakjm/Talkbox#1]
Windows 10
Java Version -1.8_144

Bug Description:

When opening the file system panel, the sizing is not responsive to the Windows operating system.
For example, the view port is miniature and you need to use the scrollbar to maneuver and see the icons.

This is not a pleasurable user experience . 

Category:

Enhancement.

**Comment by rohantalkad747** [comment]
What file system panel are you referring to? The "File Chooser"?

**Comment by Jakjm** [comment]
Yeah, that's what he's referring to. I'll look into fixing this soon

**Comment by Jakjm** [comment]
The latest update has fixed this issue, the File Selector now has 4 buttons per row and formats text in a visually appealing way.
